### ISSUE TITLE
could you give an explaination on how the router works?

### ISSUE THREAD

**Issue by drriguz** [spriet2000/vertx-http-router#1]
Hi, 
I'm currently working on a java mvc framework, this router is what exactly I want.However, I'm not sure how it's designed,I printed the tree, but it seems that it's not the same as the go version of [httprouter](https://github.com/julienschmidt/httprouter).
```
Priority   Path             Handle`
9          \                *<1>
3          ├s               nil
2          |├earch\         *<2>
1          |└upport\        *<3>
2          ├blog\           *<4>
1          |    └:post      nil
1          |         └\     *<5>
2          ├about-us\       *<6>
1          |        └team\  *<7>
1          └contact\        *<8>
```
is this router designed as the above tree structure?besides, are you going to support regex matching, such as `/blog/:post{\d+}/add`?
thanks.

**Comment by spriet2000** [comment]
sorry, i didn't  see your comment earlier :> 
you can use the printTree(tree) method in the tests to see the structure of the tree. its something like you wrote.
about the regex, i have no plans to implement regex stuff currently.
thanks!
